// flow-typed signature: b461134602ddde0e9e7e72db8c72ce01
// flow-typed version: <<STUB>>/extenso_v^2.0.1/flow_v0.151.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'extenso'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'extenso' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'extenso/dist/extenso' {
  declare module.exports: any;
}

declare module 'extenso/dist/extenso.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'extenso/dist/extenso.js' {
  declare module.exports: $Exports<'extenso/dist/extenso'>;
}
declare module 'extenso/dist/extenso.min.js' {
  declare module.exports: $Exports<'extenso/dist/extenso.min'>;
}
